sudo: false
language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

env:
  - REQUIREMENTS=django-17
  - REQUIREMENTS=django-18
  - REQUIREMENTS=django-master

matrix:
  allow_failures:
    - env: REQUIREMENTS=django-master
  exclude:
    - python: "3.2"
      env: REQUIREMENTS=django-master
    - python: "3.3"
      env: REQUIREMENTS=django-master

install:
  - pip install tox

script:
  - tox -e py-$REQUIREMENTS
